version: '3.9'
services:

#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:20.0.2-1
#    volumes:
#      - ./keycloak/import:/opt/keycloak/data/import
#    ports:
#      - '8070:8080'
#    command: "start-dev --import-realm"
#    environment:
#      DB_VENDOR: postgres
#      DB_ADDR: ${KEYCLOAK_DB_URL}
#      DB_PORT: ${KEYCLOAK_DB_PORT}
#      DB_DATABASE: keycloak
#      DB_USER: ${KEYCLOAK_DB_USER}
#      DB_PASSWORD: ${KEYCLOAK_DB_PASS}
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: 'S373Y91YQuf'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    networks:
#      - rede_digitalmoney

  service-discovery:
    container_name: service-discovery
    image: reneralmeida/service-discovery
    restart: unless-stopped
    ports:
      - "8761:8761"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede_digitalmoney

  users-service:
    container_name: users-service
    image: reneralmeida/users-service
    restart: unless-stopped
    depends_on:
      - service-discovery
    env_file:
      - .env
    ports:
      - ${USR_SVC_PORT}:${USR_SVC_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede_digitalmoney

  account-service:
    container_name: account-service
    image: renerbackend/accounts-service
    restart: unless-stopped
    depends_on:
      - service-discovery
    env_file:
      - .env
    ports:
      - ${ACC_SVC_PORT}:${ACC_SVC_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede_digitalmoney

networks:
  rede_digitalmoney:
