version: '3.9'
services:

# Para conseguir fazer o pull das imagens foi gerado um deploy token (read-only) com data de expiração (3 de maio):
# docker login registry.gitlab.com
# username: t2g2-backend
# password: GewFPSFPPwUQTkfBy-Zz

# Nosso projeto teve o Keyloak hospedado na Azure (graças ao estimado colega Ronilson) da Sprint II até metade da Sprint IV,
# onde a transferimos para a AWS em nosso ambiente Kubernetes.
#  keycloak:
#    container_name: keycloak
#    image: registry.gitlab.com/reneralmeida/pi-ii/keycloak
#    volumes:
#      - ./keycloak/import:/opt/keycloak/data/import
#      - ./keycloak/certs/:/etc/x509/https
#    restart: unless-stopped
#    env_file:
#      - .keycloak-env
#    ports:
#      - '8070:8080'
#      - '8443:8443'
#    command: "-v start --https-protocols=TLSv1.3,TLSv1.2 --import-realm"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    networks:
#      - rede_digitalmoney

  service-discovery:
    container_name: service-discovery
    image: registry.gitlab.com/reneralmeida/pi-ii/service-discovery
    restart: unless-stopped
    ports:
      - "8761:8761"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede_digitalmoney

  mail-service:
    container_name: mail-service
    image: registry.gitlab.com/reneralmeida/pi-ii/mail-service
    restart: unless-stopped
    depends_on:
      - service-discovery
    env_file:
      - .mail-env
    ports:
      - "8090:8090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede_digitalmoney

  users-service:
    container_name: users-service
    image: registry.gitlab.com/reneralmeida/pi-ii/users-service
    restart: unless-stopped
    depends_on:
      - service-discovery
    env_file:
      - .env
    ports:
      - ${USR_SVC_PORT}:${USR_SVC_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede_digitalmoney

  account-service:
    container_name: account-service
    image: registry.gitlab.com/reneralmeida/pi-ii/accounts-service
    restart: unless-stopped
    depends_on:
      - service-discovery
    env_file:
      - .env
    ports:
      - ${ACC_SVC_PORT}:${ACC_SVC_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede_digitalmoney

networks:
  rede_digitalmoney:
