version: '3.9'
services:

  postgres:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "S373Y91YQuf"
    ports:
      - "5432:5432"
    networks:
      - rede_digitalmoney
    volumes:
      - db:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.2-1
    ports:
      - '8070:8080'
    command: "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 'S373Y91YQuf'
      KC_DB: postgres
      KC_DB_PASSWORD: 'S373Y91YQuf'
      KC_DB_USERNAME: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    networks:
      - rede_digitalmoney

  db_service:
    container_name: db_users
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'users-service'
      MYSQL_USER: 'users-service'
      MYSQL_PASSWORD: 'users-service'
      MYSQL_ROOT_PASSWORD: 'strongest-password'
    ports:
      - "3306:3306"
    volumes:
      - db-mysql:/var/lib/mysql
    networks:
      - rede_digitalmoney

networks:
  rede_digitalmoney:
    driver: bridge
volumes:
  db:
  db-mysql: