apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: default
  labels:
    app: users
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30081
  selector:
    app: users