apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: default
  labels:
    app: users
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: users
  type: ClusterIP