apiVersion: apps/v1
kind:
  Deployment
metadata:
  name: users-service
  namespace: default
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: reneralmeida/users-service:latest
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: CLIENT_ID_BACKEND
              value: backend
            - name: CLIENT_ID_USERS
              value: users-service
            - name: CLIENT_SECRET_BACKEND
              value: A3OQ2NR9S85xMVMQ88t2CfEciVbXb2ol
            - name: CLIENT_SECRET_USERS
              value: thR85ow0FqYJmJTan2wTdNaX9gCxwLbf
            - name: JWT_ISSUER_URI
              value: https://auth.pi.ronilsonalves.com/realms/digitalmoney
            - name: KEYCLOAK_SERVER_URL
              value: https://auth.pi.ronilsonalves.com/
            - name: REALM_TOKEN_URI
              value: https://auth.pi.ronilsonalves.com/realms/digitalmoney/protocol/openid-connect/token
            - name: USR_SVC_DB_URL
              value: dbusers.pi.ronilsonalves.com
            - name: USR_SVC_DB_USER
              value: users-service
            - name: USR_SVC_DB_PASS
              value: 6hpFI32U74D3
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred