apiVersion: apps/v1
kind:
  Deployment
metadata:
  name: service-discovery
  namespace: default
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: digitalmoneydev.azurecr.io/service-discovery:develop
          ports:
            - name: http
              containerPort: 8761
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret