apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: default
  labels:
    app: eureka
spec:
  ports:
    - name: http
      port: 8761
      targetPort: 8761
  selector:
    app: eureka
  type: ClusterIP