apiVersion: v1
kind: Service
metadata:
  name: mail-service
  namespace: default
  labels:
    app: mail
spec:
  type: NodePort
  ports:
    - port: 8090
      nodePort: 30090
  selector:
    app: mail