apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: default
  labels:
    app: accounts
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30082
  selector:
    app: accounts