apiVersion: apps/v1
kind:
  Deployment
metadata:
  name: account-service
  namespace: default
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: eureka
          image: digitalmoneydev.azurecr.io/service-discovery:develop
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret