apiVersion: apps/v1
kind:
  Deployment
metadata:
  name: account-service
  namespace: default
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: renerbackend/accounts-service:latest
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: CLIENT_ID_BACKEND
              value: backend
            - name: CLIENT_SECRET_BACKEND
              value: A3OQ2NR9S85xMVMQ88t2CfEciVbXb2ol
            - name: JWT_ISSUER_URI
              value: https://auth.pi.ronilsonalves.com/realms/digitalmoney
            - name: KEYCLOAK_SERVER_URL
              value: https://auth.pi.ronilsonalves.com/
            - name: REALM_TOKEN_URI
              value: https://auth.pi.ronilsonalves.com/realms/digitalmoney/protocol/openid-connect/token
            - name: ACC_SVC_DB_URL
              value: dbaccounts.pi.ronilsonalves.com
            - name: ACC_SVC_DB_USER
              value: accounts-service
            - name: ACC_SVC_DB_PASS
              value: 05L7zz7emrXY
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred2